### PR TITLE
fixes for netcdf/HDF5 file vars (strided) read/write performance and unlimited dimension issues

### LINKED ISSUE #448: nc_put_vars_double (or float) fails in parallel
### Environment Information
* What platform are you using? (please provide specific distribution/version in summary)
  * [x] Linux
  * [ ] Windows
  * [x] OSX
  * [ ] Other
  * [ ] NA
* 32 and/or 64 bit?
  * [ ] 32-bit
  * [x] 64-bit
* What build system are you using?
  * [x] autotools (`configure`)
  * [x] cmake
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [ ] Yes (please attach to this issue, thank you!)
  * [ ] No
  * [x] Not at this time

### Summary of Issue
NOTE: my dvarput.c is modified from 4.5.1-devel as described in #447 -- the early return if nels==0 has been removed.

If `nc_put_vars_double` is called in parallel with stride != 1 and some processors have data to output and some do not *and* netcdf-4 (hdf5-based) output is being used in a collective mode, then the code will hang since only the processors with data to output will call down in to the `H5Dwrite` function.  This function assumes that all processors will call whether they have data or not and uses a PMPI_Allreduce down in the call stack.

The issue arises in `NCDEFAULT_put_vars`.  If stride is 1, then everything works ok since all processors call `NC_put_vars` at line 246 of dvarput.c (4.5.1-devel)

However, if the stride is not 1, then the code falls down to the `odometer` code below that.  All processors call `odom_init`, but then the `while` is only called by the processors that have data (some lines deleted below):
```
  odom_init(&odom,rank,mystart,myedges,mystride);
  while(odom_more(&odom)) {
      int localstatus = NC_NOERR;
      localstatus = NC_put_vara(ncid,varid,odom.index,nc_sizevector1,memptr,memtype);
      memptr += memtypelen;
      odom_next(&odom);
   }
```
If netcdf-4 (hdf5-based) collective output is being done, then the code will hang down below `H5Dwrite` due to hdf5 library calling `PMPI_Allreduce`.

I don't have a suggested fix for this issue. I tried rewriting my code to use `nc_put_vara_double` instead, but that is not easily done for this particular call.

This does work if I use pnetcdf non-collective output and probably also netcdf-4 non-collective

### LINKED ISSUE #1374: Very strange runtime behaviour
### Environment Information

* What platform are you using? (please provide specific distribution/version in summary)
  * [x] Linux
  * [ ] Windows
  * [ ] OSX
  * [ ] Other
  * [ ] NA
* 32 and/or 64 bit?
  * [ ] 32-bit
  * [x] 64-bit
* What build system are you using?
  * [ ] autotools (`configure`)
  * [x] cmake
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [x] Yes (see https://github.com/xy124/parflow/blob/parFlowVR/flowvr/netcdf-writer/main.c)
  * [ ] No
  * [ ] Not at this time

### Summary of Issue
When using parallel netCDF I get good runtimes on 1,3,4,5,6,7,8 nodes (16 cores each) but when using 2 nodes the time for file writes is about 10 times higher. This is reproducible.
Writing wall time on **one node**:
for the nc_put_vara_double in main.c:229 : ca **4,5 seconds**
Writing wall time on **two nodes**:
for the nc_put_vara_double in main.c:229 : ca **45 seconds**
Writing wall time on **three nodes**:
for the nc_put_vara_double in main.c:229 : ca **5 seconds**

### Steps to reproduce the behavior
very short version:
```C
nc_create_par(file_name, NC_NETCDF4 | NC_MPIIO, MPI_CommWorld, MPI_INFO_NULL, &ncID);
nc_var_par_access(current_file_id, time_var_id, NC_COLLECTIVE);
 
nc_put_vara_double(current_file_id, time_var_id, start, count, &(m->time));
```
I even tried with multiple sizes (`data` about 4 MB up to 40MB) with the same results.

The source code is found here: https://github.com/xy124/parflow/blob/parFlowVR/flowvr/netcdf-writer/main.c . One of those is executed per compute Node! (And it gets data to write from other cores
*A very small explication of the linked source code:
We wait for messages (fca_wait()) that contains data to write into netcdf files. These messages are then read and written (`nc_put_vara_double(current_file_id, variable_var_id, start, count, data);`) That works very fine but on 2 nodes as mentioned this takes very long.*

I'm very thankful for every idea what I could try. Is there a good realtime profiler that works with netcdf? I tried google perf tools with no success.

### LINKED ISSUE #1380: HDF5 stride has different semantics than netcdf stride semantics wrt unlimited.
In PR https://github.com/Unidata/netcdf-c/pull/1001
we converted the netcdf-4 code to use the HDF5 hyperslab
operators to speed up strided access (stride > 1). This replaces
an older element-at-a-time code implementing strided access.

It appears that the HDF5 stride semantics did not exactly match the older
stride semantics in (at least) the following case:
1. A variable has an unlimited dimension
2. The space allocated in the HDF5 dimension for this variable
    is smaller than the current (maximum) UNLIMITED value.
3. A vars (stride > 1) read is performed that accessed values past
   the allocated space for the variable, but inside the space size implied
   by unlimited.
4. For some reason, this causes the last legal value to be misread even though
    it has a defined value. Instead, the fillvalue is returned.

The attached set of files shows this. If you use h5dump on the .nc file,
it shows that the temperature variable has 50 defined values. However,
ncdump on that file shows the temperature variable has the unlimited size
of 55 values. So the netcdf program  ncRepro_WeirdStrideIssue.c attempts to
read values past the 50 defined values and somehow the netcdf-c library screws up.
The other program is a pure HDF5 program that attempts to do the same thing,
but if the count is set to 19 (as in the netcdf program) the HDF5 program fails
with an index error. 

The fix for this could be ugly.

[files.zip](https://github.com/Unidata/netcdf-c/files/3035977/files.zip)

### LINKED ISSUE #1381: Speed up NCDEFAULT_get/put_vars code
It occurs to me that we should consider improving
the performance of NCDEFAULT_get/put_vars since they
are still being used for some dispatch tables.

The current implementations operate by reading/writing
one element at a time, which is seriously inefficient.

We should explore some alternative implementations such as this.

1. Instead of reading element at a time, we allocate some larger
   block of memory that covers multiple strided elements at a time.
2. the stride code then reads one of these blocks and extracts the
   relevant strided elements.
3. Cost is memory of the block (per-call to get_vars). - should
    we keep a blockcache
4. For writing, we would read the block, then insert the
   strided elements, and then write out the whole block.

Anyone have any other suggestions for speed up?

### LINKED ISSUE #1757: Slicing very slow in 4.7.4 (reported)
Mirroring an issue from the python interface, which hooks into the underlying C library.

* https://github.com/Unidata/netcdf4-python/issues/1018

In a nutshell, array slicing in 4.7.4 has been reported as being orders of magnitude slower than in 4.7.3.  Creating an issue here in the C library to make it easier to keep track of.

### LINKED ISSUE #1877: NetCDF slow writes when using the stride parameter.
**NetCDF versions in which we have observed this issue:**
* Observed in **4.7.1**, **4.6.3**, and **4.3.3.1**. There is a considerable improvement in 4.7.1 but, strided writes are still slower than just using loops and iteratively writing the same values at the same locations.

**Platform information:**
* Tested on Linux lsdbgl28141glnxa64 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

**Description of the issue:**
* We have observed slower write speeds when using the "nc_put_vars_double()" function to write to a NetCDF4-classic file using the "stride" feature. I created a standalone file to reproduce the issue and tested it on versions 4.7.3, 4.6.1, and 4.3.3.1 of the NetCDF library. The following are some sample runtimes that I got both by using the stride feature and without it:

ver 4.3.3.1: 
Strided: 184514115 microseconds 
Looped: 336884 microseconds

ver 4.6.1: 
Strided: 175383093 microseconds 
Looped: 340540 microseconds

ver 4.7.3: 
Strided: 5841009 microseconds 
Looped: 370361 microseconds

The code attached writes a 5184 x 228 x 40 matrix to a NetCDF file with dimensions: 5184 x 228 X (unlimited), using the nc_put_vars_double() function of NetCDF by: 
a. Using the stride parameter i.e. specifying the stride vector as (1, 1, 5). 
b. By looping along the z-axis and iterating the starting points of the writes as (0, 0, i * 5) while keeping the stride vector as (1, 1, 1).
[NetCDF_slow_stided_writes-main.zip](https://github.com/Unidata/netcdf-c/files/5465451/NetCDF_slow_stided_writes-main.zip)

### LINKED ISSUE #1947: 'nccopy' much slower in 4.7.4 vs. 4.6.1
I'm testing 'nccopy' to compress a ~ 3 GB netCDF-3 file. 

On a local server with nccopy from netCDF library version 4.6.1, "time" reports about a minute to compress the file:

prompt> time nccopy -d1 -s 3test.nc ncc_out.nc
55.618u 4.231s 1:00.89 98.2%    0+0k 6115200+2831800io 30pf+0w

On the NCAR CISL DAV cluster, nccopy is from netCDF library version 4.7.4. The same command

prompt> time nccopy -d1 -s 3test.nc ncc_out.nc

Has now been running for more than 30 minutes with the expected output file 15% done.

I've seen reports of this behavior here and the solution seemed to be getting rid of any UNLIMITED dimensions. That doesn't seem like a good solution to me.

Any guidance/suggestions most welcome! Thanks!

### LINKED ISSUE #1977: netCDF 4.8.0 ncgen breaks on CDL type "long"?
netCDF 4.8.0 appears to break NCO builds because `ncgen` no longer supports the type "long" as a synonym for "int" in CDL files. I did not notice this backwards-incompatibility in the 4.8.0 release notes. Is it intentional?

With latest snapshot:
```
zender@glace:~/nco/data$ ncgen -v
ncgen: option requires an argument -- 'v'
Usage: ncgen [-1] [-3] [-4] [-5] [-6] [-7] [-b] [-d] [-D debuglevel] [-h] [-k kind ] [-l language=b|c|f77|java] [-M <name>] [-n] [-o outfile] [-P] [-x] [-N datasetname] [-L loglevel] [-H] [-W generate whole var upload] [file ... ]
netcdf library version 4.8.1-development of Mar 30 2021 16:12:40 $
zender@glace:~/nco/data$ ncgen -o in.nc in.cdl
Undefined name (line 642): long
zender@glace:~/nco/data$ 
```
With 4.7.4 and earlier:
```
zender@sastrugi:~/nco/data$ ncgen -v
ncgen: option requires an argument -- v
Usage: ncgen [-1] [-3] [-4] [-5] [-6] [-7] [-b] [-B buffersize] [-d] [-D debuglevel] [-h] [-k kind ] [-l language=b|c|f77|java] [-M <name>] [-n] [-o outfile] [-P] [-x] [-N datasetname] [-L loglevel] [-H] [file ... ]
netcdf library version 4.7.4 of Dec 16 2020 23:04:20 $
zender@sastrugi:~/nco/data$ ncgen -o in.nc in.cdl
zender@sastrugi:~/nco/data$ 
```

Input file in.cdl is here: https://github.com/nco/nco/blob/master/data/in.cdl

### LINKED ISSUE #2354: Add new --enable/disable-zstandard configure option
This assumes #2348 is merged, and #2353 is also adopted.

Currently the configure looks for the zstandard library and decides whether or not to install zstandard based on whether or not it is found. This is somewhat random for the installer (it might be installed, it might not, from system to system).

To make this more reliable we can add an option --enable/disable-zstandard. If --enable-zstandard is used, then the zstandard library is required (just as curl is required if --enable-dap is used).

So the user can do --enable-zstandard on every machine. If the zstandard library is not installed, then the configure will error out, and tell the user to install it, or build with --disable-zstandard.

In this way, the user can specify a preference and is sure to get what they want every time.

### LINKED ISSUE #2668: heap-buffer-overflow in NC4_get_vars netcdf/libhdf5/hdf5var.c
heap-buffer-overflow in NC4_get_vars netcdf/libhdf5/hdf5var.c

Built from git commit hash 63150df
OS: Ubuntu 20.04
Compiler: clang version 11.0

Build options:
- Shared library disabled
CC=clang
CXX=clang++
CFLAGS="-g -fno-inline -fsanitize=address"
CXXFLAGS="-g -fno-inline -fsanitize=address"
LDFLAGS="$LDFLAGS -fsanitize=address"
ASAN_OPTIONS=abort_on_error=1

Command: ./ncdump pov

POV file:
[pov.zip](https://github.com/Unidata/netcdf-c/files/11013243/pov.zip)

Stack trace:
```
==3254300==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000011018 at pc 0x00000043bdad bp 0x7ffcad464cd0 sp 0x7ffcad464480
READ of size 24 at 0x602000011018 thread T0
#0 0x43bdac in __interceptor_memcpy.part.0 /home/chaitra/aflgo-top/build/llvm_tools/llvm-11.0.0.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:808:5
#1 0x7f85eafcad32 in H5VM_memcpyvv (/lib/x86_64-linux-gnu/libhdf5_serial.so.103+0x29bd32)
#2 0x7f85eadcadee  (/lib/x86_64-linux-gnu/libhdf5_serial.so.103+0x9bdee)
#3 0x7f85eade6f79  (/lib/x86_64-linux-gnu/libhdf5_serial.so.103+0xb7f79)
#4 0x7f85eade77b9 in H5D__select_read (/lib/x86_64-linux-gnu/libhdf5_serial.so.103+0xb87b9)
#5 0x7f85eadc536e  (/lib/x86_64-linux-gnu/libhdf5_serial.so.103+0x9636e)
#6 0x7f85eade0513 in H5D__read (/lib/x86_64-linux-gnu/libhdf5_serial.so.103+0xb1513)
#7 0x7f85eade0a0c in H5Dread (/lib/x86_64-linux-gnu/libhdf5_serial.so.103+0xb1a0c)
#8 0x666b87 in NC4_get_vars netcdf/libhdf5/hdf5var.c:2102:13
#9 0x663bf2 in NC4_get_vara netcdf/libhdf5/hdf5var.c:1402:12
#10 0x563a50 in NC_get_vara netcdf/libdispatch/dvarget.c:104:12
#11 0x5679eb in nc_get_vara netcdf/libdispatch/dvarget.c:750:11
#12 0x50d0bc in print_rows netcdf/ncdump/vardata.c:478:2
#13 0x50cf3b in print_rows netcdf/ncdump/vardata.c:463:6
#14 0x50cf3b in print_rows netcdf/ncdump/vardata.c:463:6
#15 0x50cfdb in print_rows netcdf/ncdump/vardata.c:467:2
#16 0x50c95f in vardata netcdf/ncdump/vardata.c:588:5
#17 0x503794 in do_ncdump_rec netcdf/ncdump/ncdump.c:1965:7
#18 0x4fda26 in do_ncdump netcdf/ncdump/ncdump.c:2047:4
#19 0x4fb3b2 in main netcdf/ncdump/ncdump.c:2490:7
#20 0x7f85ea740082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
#21 0x41fe2d in _start (netcdf/ncdump/ncdump+0x41fe2d)
0x602000011018 is located 0 bytes to the right of 8-byte region [0x602000011010,0x602000011018)
allocated by thread T0 here:
#0 0x4c4f4f in malloc /home/chaitra/aflgo-top/build/llvm_tools/llvm-11.0.0.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
#1 0x7f85eae39641  (/lib/x86_64-linux-gnu/libhdf5_serial.so.103+0x10a641)
SUMMARY: AddressSanitizer: heap-buffer-overflow /home/chaitra/aflgo-top/build/llvm_tools/llvm-11.0.0.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:808:5 in __interceptor_memcpy.part.0
Shadow bytes around the buggy address:
0x0c047fffa1b0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
0x0c047fffa1c0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
0x0c047fffa1d0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
0x0c047fffa1e0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
0x0c047fffa1f0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
=>0x0c047fffa200: fa fa 00[fa]fa fa fa fa fa fa fa fa fa fa fa fa
0x0c047fffa210: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
0x0c047fffa220: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
0x0c047fffa230: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
0x0c047fffa240: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
0x0c047fffa250: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
Addressable:           00
Partially addressable: 01 02 03 04 05 06 07
Heap left redzone:       fa
Freed heap region:       fd
Stack left redzone:      f1
Stack mid redzone:       f2
Stack right redzone:     f3
Stack after return:      f5
Stack use after scope:   f8
Global redzone:          f9
Global init order:       f6
Poisoned by user:        f7
Container overflow:      fc
Array cookie:            ac
Intra object redzone:    bb
ASan internal:           fe
Left alloca redzone:     ca
Right alloca redzone:    cb
Shadow gap:              cc
==3254300==ABORTING
```

### LINKED ISSUE #2721: nc_get_vars incredibly slow in Windows compared to Linux
OS: Windows 10
NetCDF version: 4.9.1

I am trying to read a 3D double variable (2000 x 512 x 512) from a netCDF4 file with the following parameters:
start = {0,0,0}
count[] = {1000, 256, 256};
stride[] = {2, 2, 2};
chunk size: {20, 10, 10}
shuffle: no
deflate : yes
deflate_level : 6

I time the call to nc_get_vars.
On Debian 11, it takes ~25 seconds.
On Windows 10, it takes ~130 seconds.

I would expect Windows to be slightly slower, but >5x slowdown is unexpected. 
I see similar slowdowns with 'nc_get_vars_double'

On the contrary, using 'nc_get_var_double' or 'nc_get_var' to read the whole variable is significantly faster (~3 sec on Linux, and ~1 sec on Windows)

1. Is there a way to optimize the performance of 'nc_get_vars' or 'nc_get_vars_double' so that Windows performance is closer to Linux performance?

2. Is reading the whole variable using 'nc_get_var' to memory and then slicing it later an option? I have seen that there were some discussions regarding this (https://github.com/Unidata/netcdf-c/issues/908) and that a submission was made to make strided reads faster. But for my variable, reading the whole variable still seems to be significantly faster than strided reads (especially on Windows)

Please find the link to the nc file [here](https://mathworks-my.sharepoint.com/:u:/p/abaruah/EYcT4lfwEI1AhIOP-W3YsToBDF61Bi8vYfL5TC7hm64w0w?e=3MU48c).
Here is my code:

```
#include <stdio.h>
#include <string.h>
#include <netcdf.h>
#include <cstdlib>
#include <iostream>
#include <chrono>

int
main()
{
    int status;
    int ncid;
    int varid;

    int elems_x = 256;
	int elems_y = 256;
	int elems_z = 1000;
    double* outData = (double*)malloc (elems_x*elems_y*elems_z*sizeof(double));

    size_t start[] = {0, 0, 0};
    size_t count[] = {1000, 256, 256};
    ptrdiff_t stride[] = {2, 2, 2};

    
    // open the NetCDF-4 file
    status = nc_open("repro_nc4file.nc", NC_NOWRITE, &ncid);
    if(status != NC_NOERR) {
         printf("Could not open file.\n");
    }
   
    // get the varid 
    status = nc_inq_varid(ncid, "my_var", &varid);
    printf("status after inq var = %d\n", status);
    printf("varid = %d\n", varid);

    // get the strided subset
	auto timestart = std::chrono::high_resolution_clock::now();
    status = nc_get_vars(ncid, varid, start, count, stride, outData);
	auto timeend = std::chrono::high_resolution_clock::now();
	auto duration = std::chrono::duration_cast<std::chrono::seconds>(timeend - timestart);
	std::cout << "Execution time: " << duration.count() << " seconds" << std::endl;
    printf("status after getting strided subset = %d\n", status);

    // close the file 
    status = nc_close(ncid);
    printf("status after close = %d\n", status);

    printf("End of test.\n\n");

    return 0;
}

```

### LINKED ISSUE #3123: `read` operations cause too many disk reads with unlimited dimensions
@lesserwhirls - the problem as far as I can tell exists in netcdf-java as well.

This is a repeat of [this issue](https://github.com/Unidata/netcdf-fortran/issues/465) which can probably be closed in favor of this one.

The problem: we're hosting netcdf-classic files with in EFS and reading them from EC2, so we're charged per bytes read. The charges have been unexpectedly high (order of magnitude) for reads from our datasets with unlimited dimensions.

I've attached the results of some testing I've done locally on my mac using `fs-usage`, input files, the output of those tests, and the python script I used to count bytes read. The short summary is output from reading a fixed dimension dataset are about what we expect with both ncdump and toolsui, but way too high when reading from a record dataset.

[test_disk_reads.zip](https://github.com/user-attachments/files/19764288/test_disk_reads.zip)

### LINKED ISSUE #3134: nccopy -c -u prevents from rechunking the data
**Versions of** 

``` bash
❯ nccopy
..
netCDF library version 4.9.2 of Aug 31 2024 11:17:57 $
```

```
  uname -a
Linux phronesis 6.6.72-1-lts #1 SMP PREEMPT_DYNAMIC Fri, 17 Jan 2025 14:04:26 +0000 x86_64 GNU/Linux
```

**Issue**

I think that using `nccopy` to rechunk data via the `-c` option _along with_ `-u` prevent the rechunking to really happen.  A simple test case : 

A hint already in the time it takes to complete the "copy" : 

``` bash
❯ time nccopy -c time/48,lat/4,lon/4 -u -d 1 -w SISin200001010000004231000101MA_European_framgment.nc test2.nc

real	0m0.758s
user	0m0.712s
sys	0m0.041s

❯ time nccopy -c time/48,lat/4,lon/4 -d 1 -w SISin200001010000004231000101MA_European_framgment.nc test3.nc

real	1m6.757s
user	1m6.407s
sys	0m0.240s
``` 
and then looking at the output files via Xarray, for example

an "original" file is : 

``` python
xr.open_dataset('SISin200001010000004231000101MA_European_framgment.nc').SIS.encoding
{'dtype': dtype('int16'),
 'zlib': True,
 'szip': False,
 'zstd': False,
 'bzip2': False,
 'blosc': False,
 'shuffle': False,
 'complevel': 4,
 'fletcher32': False,
 'contiguous': False,
 'chunksizes': (1, 609, 1109),
 'preferred_chunks': {'time': 1, 'lat': 609, 'lon': 1109},
 'source': '/mnt/sandbox/european_fragment/netcdf/test/SISin200001010000004231000101MA_European_framgment.nc',
 'original_shape': (48, 609, 1109),
 'missing_value': np.int16(-999),
 '_FillValue': np.int16(-999)}
```

and two rechunked test files : 

``` python
xr.open_dataset('test2.nc').SIS.encoding
{'dtype': dtype('int16'),
 'zlib': True,
 'szip': False,
 'zstd': False,
 'bzip2': False,
 'blosc': False,
 'shuffle': False,
 'complevel': 1,
 'fletcher32': False,
 'contiguous': False,
 'chunksizes': (24, 305, 555),
 'preferred_chunks': {'time': 24, 'lat': 305, 'lon': 555},
 'source': '/mnt/sandbox/european_fragment/netcdf/test/test2.nc',
 'original_shape': (48, 609, 1109),
 'missing_value': np.int16(-999),
 '_FillValue': np.int16(-999)}
```

``` python
xr.open_dataset('test3.nc').SIS.encoding
{'dtype': dtype('int16'),
 'zlib': True,
 'szip': False,
 'zstd': False,
 'bzip2': False,
 'blosc': False,
 'shuffle': False,
 'complevel': 1,
 'fletcher32': False,
 'contiguous': False,
 'chunksizes': (48, 4, 4),
 'preferred_chunks': {'time': 48, 'lat': 4, 'lon': 4},
 'source': '/mnt/sandbox/european_fragment/netcdf/test/test3.nc',
 'original_shape': (48, 609, 1109),
 'missing_value': np.int16(-999),
 '_FillValue': np.int16(-999)}
```

Excuse the ignorance if this is a known behavior.

### PR DESCRIPTION
**Pull request by edhartnett**
This is a very small set of bugfixes to two code files (nc4hdf5.c and nc4var.c) which addresses the strided read and write performance and unlimited dimension problems which have been reported over the years. These are problems that both Dennis and I spent many hours trying to fix, but to no avail. Claude 4.6 found the problem in minutes.

These performance problems resulted in many issues over the years. I believe I got all of them, but more historical ones may pop up.

It should be noted that this AI assist was enabled by:
* existing strong unit tests of netcdf-c
* good documentation in (these parts of) the code
* the detailed issues, in which we reported to each other and the community our (lack of) progress, what we tried, what tests we added

Given this rich context, the AI was able to find the answer by piecing together the many tiny clues scattered in our results and attempts. Pulling together disparate details from different sources, claude was able to pinpoint the exact bug.

Fixes #448
Fixes #1381 
Fixes #1757 
Fixes #2668
Fixes #1380
Fixes #3123
Fixes #2721

To confirm this test, I first committed the test to this PR, which then failed CI, as expected. Then I applied the fix and now the PR passes, demonstrating that the test catches the bug (at last!)

These related issues were already resolved in previous fixes (mostly by Dennis), as demonstrated by tests or other investigations in this PR:
Fixes #1977 
Fixes #1947 
Fixes #1877 
Fixes #3134
Fixes #1374
Fixes #2354

### CODE REVIEW

**Comment by edhartnett** [comment]
@WardF this is the next PR that should be merged. It is ready to go.

**Comment by edhartnett** [comment]
@WardF hopefully this PR can be merged soon. In addition to the fixes in PR #3330. I have a bunch of VLEN and compoound type fixes waiting to go...

**Comment by WardF** [comment]
Yup, I was evaluating it last night/looking at it again now. I have a couple things in regards to 32-bit platforms I want to double check and then we can see about getting it merged!

**Comment by edhartnett** [comment]
@WardF would you like 32-bit testing in the CI? 

```
Can GitHub Actions Test 32-bit Platforms?
Yes, it is feasible via two approaches:

Option 1 — QEMU emulation (same approach as big-endian)
The run_tests_bigendian.yml already does this using uraimo/run-on-arch-action@v2. The same technique works for 32-bit Linux:

yaml
- uses: uraimo/run-on-arch-action@v2
  with:
    arch: armv7   # or i386
    distro: ubuntu22.04
Supported 32-bit arches by that action: armv6, armv7, i386. This runs natively on the GitHub ubuntu-latest runner — no special hardware needed. The big-endian workflow already proves the pattern works.

Limitation: QEMU is slow (2–5× compile time penalty) and for i386 specifically it can be tricky because the HDF5 configure runs test programs under QEMU — same problem mentioned in the big-endian workflow comments, which is why they use the apt-packaged HDF5 there.

Option 2 — MinGW 32-bit (Windows runner, native execution)
MSYS2 supports MINGW32 and CLANG32 environments. The run_tests_win_mingw.yml already has CLANG64 commented out; adding MINGW32 to the matrix would give native 32-bit Windows testing with no emulation overhead:

yaml
matrix:
  msystem: [ MINGW64, UCRT64, MINGW32 ]
MINGW32 gives a real i686-w64-mingw32 GCC toolchain. HDF5 packages are available from the MSYS2 repos. This is probably the lowest-effort path to 32-bit CI coverage.

Recommendation
The two most practical additions:

MINGW32 in run_tests_win_mingw.yml — one line added to the matrix, native execution, covers off_t/size_t truncation bugs, pointer width assumptions, and 32-bit Windows ABI issues. Low cost.
i386 QEMU job (modeled on the s390x workflow) — covers 32-bit Linux, tests off_t handling in the autotools/classic builds, good complement to the Windows 32-bit job. Moderate cost due to emulation speed.
The main class of bugs these would catch: size_t/off_t implicit truncations from 64-bit values, pointer-sized integer assumptions, and any printf/scanf format string mismatches (%ld vs %lld). These are exactly the kinds of latent bugs that have historically surfaced in netCDF-C when users try to deploy on 32-bit embedded or legacy systems.

```

**Comment by WardF** [comment]
The issue is not the 32-bit testing, although I'll be wiring it into our docker-based infrastructure.  It took me a good chunk of time to put my finger on what was bothering me here, I'll go add a review. There's an overflow we might hit more readily on 32-bit platforms with small-but-reasonable chunk sizes; once that's corrected, we'll be able to get this merged.

**Comment by edhartnett** [comment]
@WardF is there some other testing (that is, other than the GitHub CI for netcdf-c?)

For example, are you testing with HDF5-2.0.0 anywhere?

**Comment by edhartnett** [comment]
@WardF this failed due to intermittent DAP4 test error. I'm rerunning.

This PR has been modified as requested and is read to merge.

File: libhdf5/hdf5var.c [hunk 1]
```diff
@@ -2032,7 +2039,28 @@ NC4_get_vars(int ncid, int varid, const size_t *startp, const size_t *countp,
                 if (start[d2] >= (hssize_t)fdims[d2])
                     fill_value_size[d2] = count[d2];
                 else if (endindex >= fdims[d2])
-                    fill_value_size[d2] = count[d2] - ((fdims[d2] - start[d2])/stride[d2]);
```
Comment (WardF) [inline libhdf5/hdf5var.c]: For future reference, AI is often overly verbose.  Instructions to remain informative but also emphasizing conciseness benefit.  GenAI tools are great, but the benefit the most when the output is bite-sized and easy to digest.
