### PR TITLE
moved tests from tst_h_atts2 into tst_xplatform2, fixed warnings and some memory issues

### LINKED ISSUE #542: tst_h_atts2.c depends on output from tst_xplatform2.c
The test tst_h_atts2.c uses pure HDF5 to confirm the contents of tst_xplatform2.c.

Instead, it would be better to just run these (few) tests at the end of tst_xplatform2.c, eliminating the dependency between these two files.

Ward, are you OK with that? I have the new tst_xplatform2.c working fine with the tests from tst_h_atts2.c, the next step is to remove tst_h_atts2.c and also remove it from Makefile.am and CMakelists.txt.

Sound OK?

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #542.
Part of #541.

As discussed yesterday with Ward and Denis, there was a dependancy between these files. tst_h_atts2 needed tst_xplatform2 to run first, because it uses HDF5 to check the output of that test. Instead I have moved that output checking to the end of tst_xplatform2 and removed tst_h_atts2.

Also have fixed warnings in tst_xplatform2.

Also have fixed some memory problems in tst_xplatform2. Some remain (see #541). The line of test code that causes this memory issue is left commented out in this test until I can fix that memory problem.

### CODE REVIEW

File: nc_test4/tst_xplatform2.c [hunk 1]
```diff
@@ -209,16 +210,16 @@ check_file_3(int ncid, struct s3 *data_out)
    for (i = 0; i < DIM3_LEN; i++)
       for (j = 0; j < NUM_VL; j++)
       {
-	 if (data_in[i].data[j].len != data_in[i].data[j].len) ERR;
+	 if (data_in[i].data[j].len != data_out[i].data[j].len) ERR;
```
Comment (edhartnett) [inline nc_test4/tst_xplatform2.c]: This is an important warning fix. We were comparing data_in to data_in, which of course was always equal. We need to compare data_in to data_out to actually test results of read.

File: nc_test4/tst_xplatform2.c [hunk 2]
```diff
@@ -209,16 +210,16 @@ check_file_3(int ncid, struct s3 *data_out)
...
 		((struct s1 *)data_in[i].data[j].p)[k].y != ((struct s1 *)data_out[i].data[j].p)[k].y) ERR;
       }
 
    /* Free our vlens. */
-/*    for (i = 0; i < DIM3_LEN; i++) */
-/*       for (j = 0; j < NUM_VL; j++) */
-/* 	 nc_free_vlen(&(data_in[i].data[j])); */
+   for (i = 0; i < DIM3_LEN; i++)
+      for (j = 0; j < NUM_VL; j++)
+	 nc_free_vlen(&(data_in[i].data[j]));
```
Comment (edhartnett) [inline nc_test4/tst_xplatform2.c]: These lines are necessary to free data_in vlens.

File: nc_test4/tst_xplatform2.c [hunk 3]
```diff
@@ -476,16 +476,16 @@ main(int argc, char **argv)
...
 
       /* Write the output data as an attribute. */
       if (nc_put_att(ncid, NC_GLOBAL, S3_ATT_NAME, s3_typeid,
-		     DIM3_LEN, comp_array_of_vlen_of_comp_out)) ERR;
+   		     DIM3_LEN, comp_array_of_vlen_of_comp_out)) ERR;
 
-      /* How does it look? */
-      if (check_file_3(ncid, comp_array_of_vlen_of_comp_out)) ERR;
+      /* How does it look? Uncomment this line to see memory issue. */
+      /* if (check_file_3(ncid, comp_array_of_vlen_of_comp_out)) ERR; */
```
Comment (edhartnett) [inline nc_test4/tst_xplatform2.c]: If this line is uncommented, and the code built with address santizer, then a memory problem is revealed.
